---
title: "S.Fig4"
author: "Regan"
date: '2022-05-15'
---

# Load sce and directory
```{r}
sce <- readRDS("/Users/reganhamel/Documents/PhD/Publications/202X Metabo/scRNAseq/EAE/All Cremato/EAE_202X/4_finalAnnotations/sce.RDS")
dirA <- "/Users/reganhamel/Documents/PhD/Publications/202X Metabo/Figures/FigS4/"
```

# SFig4 A complex I/II genes
```{r}
dirT <- paste0(dirA, "/Complex_Genes/")
dir.create(dirT)
```

calculate complexI genes
```{r}
source("/Users/reganhamel/Documents/PhD/scRNAseq Workflow/Gene Lists/Complex Genes/Complex Genes.R")

genes <-  Complex1
names(genes)
list <- names(genes)

input <- c(strsplit(genes, " "))
input <- input[[1]]
input <- trimws(input, which = "b", whitespace = "[ \t\r\n]")
input <- input[input != ""]

input <- input[which(input %in% rownames(sce))]
input

sce$complex_logs <- colMedians(as.matrix(logcounts(sce[input])))

# plotUMAP

plotUMAP(sce, colour_by="complex_logs")
ggsave(filename = paste0(names(genes),"_MedianLogs_legend.pdf"), path = dirT, scale = 1, width = 5, height = 5, dpi = 300, limitsize = TRUE)

p <- plotUMAP(sce, colour_by="complex_logs")
AugmentPlot(plot=p, dpi=600)  #+ geom_point(aes(fill=colData(x)[c.by][,1]), pch=21, stroke = .0, alpha = 0.6, size=1)
ggsave(filename = paste0(names(genes),"_MedianLogs.pdf"), path = dirT, scale = 1, width = 5, height = 5, dpi = 300, limitsize = TRUE)
```


# Fig 1B/C: subclustered UMAPs for subcluster 4
```{r}
subsce_all <- readRDS("/Users/reganhamel/Documents/PhD/Publications/202X Metabo/scRNAseq/EAE/All Cremato/EAE_202X/6_subClustering/sce_subclustered.RDS")
```

```{r}
library(scater)
library(Seurat)
col <- "condition"

subsce <- subsce_all[[2]] # subcluster 6

p = plotUMAP(subsce, colour_by=col)

AugmentPlot(plot=p, width =5, height = 5, dpi=600)  #+ geom_point(aes(fill=colData(sce)["complex1_logs"][,1]), pch=21, stroke = .0, alpha = 0.6, size=2)
ggsave(filename = paste0(col, "_vectorFriendly.pdf"), path = file.path(dirA, "Cluster6"), scale = 1, width = 5, height = 5, dpi = 300, limitsize = TRUE)
ggsave(p, filename = paste0(col, "_legend.pdf"), path = file.path(dirA, "Cluster6"), scale = 1, width = 5, height = 5, dpi = 300, limitsize = TRUE)

```


# SFig 1D: subcluster 6 complexI genes
```{r}
source("/Users/reganhamel/Documents/PhD/scRNAseq Workflow/Gene Lists/Complex Genes/Complex Genes.R")

genes <-  Complex1
names(genes)
list <- names(genes)

input <- c(strsplit(genes, " "))
input <- input[[1]]
input <- trimws(input, which = "b", whitespace = "[ \t\r\n]")
input <- input[input != ""]

input <- input[which(input %in% rownames(subsce))]
input

subsce$complex_logs <- colMedians(as.matrix(logcounts(subsce[input])))

# plotUMAP

plotUMAP(subsce, colour_by="complex_logs")
ggsave(filename = paste0(names(genes),"_MedianLogs_legend.pdf"), path = file.path(dirA, "Cluster6"), scale = 1, width = 5, height = 5, dpi = 300, limitsize = TRUE)

p <- plotUMAP(subsce, colour_by="complex_logs")
AugmentPlot(plot=p, dpi=600)  #+ geom_point(aes(fill=colData(x)[c.by][,1]), pch=21, stroke = .0, alpha = 0.6, size=1)
ggsave(filename = paste0(names(genes),"_MedianLogs.pdf"), path = file.path(dirA, "Cluster6"), scale = 1, width = 5, height = 5, dpi = 300, limitsize = TRUE)
```

# SFig 1F: GO bar plots of select GO terms for subcluster 4
```{r}
library(stringr)

dirH <- "/Users/reganhamel/Dropbox (Cambridge University)/Lab/Regan/EAE_Metabo/FigS4/Cluster6/DEGs/GO/"
clust <- levels(factor(subsce$subcluster))

clusters <- NULL
for(i in clust) {
  input <- NULL
  try(input <- read.table(paste0(dirH,i, ".txt"), header = TRUE, sep ="\t", skip = 11))
  if(!is.null(input)) {
    name <- paste0("clust", i)
    clusters <- c(clusters, name) 
    assign(name, input)
    input <- NULL
    
  }
  input <- NULL
}


#extract just the GO and fold enrichment from each cluster & write as csv
all <- NULL
for(i in clusters) {
  input <- eval(parse(text=i))
  GO <- as.character(input$GO.biological.process.complete) 
  FDR <- input[,grep("*FDR*", names(input))]
  FE <- input[,grep("*Enrichment*", names(input))]
  FE <- str_remove(FE, "> ")
  FE <- str_remove(FE, "< ")
  FE <- trimws(FE, which = "b", whitespace = "[ \t\r\n]")
  FE <- as.numeric(FE)
  Clust <- rep(i, length(FE))
  GO_FE <- cbind(GO, FE, FDR, Clust)
  all <- rbind(all, GO_FE)
  assign(paste0("GO_FE_", i), GO_FE)
  
  write.csv(GO_FE, paste0(dirH, i, "_lim.csv" ))
  
}
```

read the saved csv of interest and plot
```{r}
clusterToPlot <- "clust6.5_lim"
data <- read.csv(paste0(dirH, clusterToPlot, ".csv"), blank.lines.skip=T)
data$nlog_FDR <- -log2(as.numeric(data$FDR))
data$logFE <- log2(as.numeric(data$FE))
#data$GO <- gsub(" \\(.*", "", data$GO)


#plot GO as a barplot (top30)
data <- data[1:4,]

pdf(file = paste0(dirH, clusterToPlot, ".pdf"), width = 6, height =2)
# Increase margin size
par(mar=c(4,20,0,0.5))

# font size
f = 0.5
x <- rev(data$nlog_FDR[order(data$FE)])
y <- rev(data$GO[order(data$FE)])


y=barplot(data$FE, names.arg = data$GO, horiz=T, las = 1, xlab = "Fold Enrichment", cex.names=f, cex.axis=f, col = "#99C1E8", xlim=c(0, max(data$FE)+0.5))
points(x, y, pch=20, cex=1)

dev.off()
```
